[package]
name = "matrix"
version = "0.1.0"
authors = ["Daniël de Kok <me@danieldk.eu>"]

[dependencies]
cfg-if = "0.1"
simd = { version = "0.2", optional = true }

[dev-dependencies]
rand = "0.4"
quickcheck = "0.6"

[features]
avx-accel = ["simd-accel"]
simd-accel = ["simd"]
